apiGateway:
  host: api.dispatch.local
dispatch:
  host: dispatch.local
  port: 443
  bootstrapUser: ci-bootstrap-user
  bootstrapPublicKey: BOOTSTRAP_PUBLIC_KEY
  faas: FAAS
  eventTransport: EVENT_TRANSPORT
  image:
    host: DOCKER_REGISTRY_HOST
    tag: IMAGE_TAG
