ingress:
  serviceType: LoadBalancer
apiGateway:
  serviceType: LoadBalancer
  host: 10.0.0.1
dispatch:
  host: 10.0.0.1
  port: 443
  bootstrapUser: ci-bootstrap-user
  bootstrapPublicKey: BOOTSTRAP_PUBLIC_KEY
  faas: FAAS
  eventTransport: EVENT_TRANSPORT
  image:
    host: DOCKER_REGISTRY_HOST
    tag: IMAGE_TAG