{{- if .Values.global.rbac.create -}}
# The role binding to combine the secret-access service account and role
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "fullname" . }}-role-binding
subjects:
- kind: ServiceAccount
  name: {{ template "fullname" . }}-service-account
roleRef:
  kind: ClusterRole
  name: {{ template "fullname" . }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
