---
resources:
- name: logs-bucket
  type: s3
  source:
    bucket: ((s3-logs-bucket-name))
    private: true
    regexp: solo-release/(.*).tar.gz
    region_name: ((s3-logs-bucket-region-name))
    access_key_id: ((s3-logs-bucket-access-key))
    secret_access_key: ((s3-logs-bucket-secret-key))

- name: ova-bucket
  type: s3
  source:
    bucket: ((s3-ova-bucket-name))
    private: false
    regexp: ova/(.*).ova
    region_name: ((s3-ova-bucket-region-name))
    access_key_id: ((s3-ova-bucket-access-key))
    secret_access_key: ((s3-ova-bucket-secret-key))

- name: dispatch-solo
  type: git
  source:
    uri: https://github.com/vmware/dispatch.git
    branch: solo

- name: dispatch-ui
  type: git
  source:
    uri: https://github.com/dispatchframework/dispatch-ui.git
    branch: master

- name: version-solo
  type: semver
  source:
    initial_version: 0.0.1
    bucket: ((s3-ci-bucket-name))
    key: dispatch-solo-version
    region_name: ((s3-ci-bucket-region-name))
    access_key_id: ((s3-ci-bucket-access-key))
    secret_access_key: ((s3-ci-bucket-secret-key))

- name: gh-release
  type: github-release
  source:
    owner: vmware
    repository: dispatch
    access_token: ((github-access-token))

jobs:
- name: major
  public: true
  serial_groups: [version]
  plan:
  - get: version
    resource: version-solo
    params: {bump: major}
  - put: version
    resource: version-solo
    params: {file: version/version}

- name: minor
  public: true
  serial_groups: [version]
  plan:
  - get: version
    resource: version-solo
    params: {bump: minor}
  - put: version
    resource: version-solo
    params: {file: version/version}

- name: patch
  public: true
  serial_groups: [version]
  plan:
  - get: version
    resource: version-solo
    params: {bump: patch}
  - put: version
    resource: version-solo
    params: {file: version/version}

- name: test-dispatch-solo
  public: true
  plan:
  - get: version
    resource: version-solo
    trigger: true
  - get: dispatch
    resource: dispatch-solo
  - task: build-binaries
    file: dispatch/ci/tasks/binaries.yml
  - task: run-tests
    file: dispatch/ci/tasks/run-tests.yml
    privileged: true
  on_failure:
    do:
    - task: Collect logs
      file: dispatch/ci/e2e/collect-logs.yml
    - put: logs-bucket
      params:
        file: dispatch-logs/*.tar.gz

- name: build-dispath-ui
  public: true
  plan:
  - get: dispatch-ui
    resource: dispatch-ui
  - task: build-ui
    file: dispatch-ui/ci/tasks/build-bundle.yml

- name: release
  public: true
  plan:
  - get: version
    resource: version-solo
    trigger: true
    passed: [test-dispatch-solo]
  - get: dispatch
    resource: dispatch-solo
    passed: [test-dispatch-solo]
  - get: dispatch-ui
    resource:  dispatch-ui
    passed: [build-dispath-ui]
  - task: prepare-version
    file: dispatch/ci/tasks/prepare-version.yml
  - task: build-binaries
    file: dispatch/ci/tasks/binaries.yml
  - task: build-ui-binaries
    file: dispatch-ui/ci/tasks/build-bundle.yml
  - put: gh-release
    params:
      name: release-context/tag
      tag: release-context/tag
      commitish: release-context/branch
      globs:
      - dispatch-binaries/dispatch-*
  - task: build-ova
    file: dispatch/ci/tasks/build-ova.yml
    privileged: true
  - put: ova-bucket
    params:
      file: dispatch-ova/*.ova
  - task: update-release-redirect
    file: dispatch/ci/tasks/update-release-redirect.yml
    params:
      AWS_ACCESS_KEY_ID: ((s3-ci-bucket-access-key))
      AWS_SECRET_ACCESS_KEY: ((s3-ci-bucket-secret-key))