---
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr


resources:
- name: dispatch
  type: pull-request
  source:
    repo: vmware/dispatch
    uri: git@github.com:vmware/dispatch.git
    access_token: ((github-access-token.dfbot))
    private_key: ((github-private-key.dfbot))
    every: true

- name: dispatch-master
  type: git
  source:
    uri: https://github.com/vmware/dispatch.git
    branch: master

jobs:
- name: dispatch-units
  public: true
  plan:
  - get: dispatch-pr
    resource: dispatch
    trigger: true
    version: every
  - put: dispatch
    params: {path: dispatch-pr, context: dispatch-units, status: pending}
    get_params: {fetch_merge: true}
  - aggregate:
    - task: syntax
      file: dispatch/ci/units/check-syntax.yml
    - task: headers
      file: dispatch/ci/units/check-headers.yml
    - task: missing-tests
      file: dispatch/ci/units/check-tests.yml
    - task: coverage
      file: dispatch/ci/units/coverage.yml
      params:
        DASHBOARD_HOST: ((dashboard-host))
    - task: swagger-generate
      file: dispatch/ci/units/swagger-generate.yml
    on_failure:
      put: dispatch
      params: {path: dispatch-pr, context: dispatch-units, status: failure}
    on_success:
      put: dispatch
      params: {path: dispatch-pr, context: dispatch-units, status: success}

- name: dispatch-update-coverage
  public: true
  plan:
  - get: dispatch
    resource: dispatch-master
    trigger: true
    version: every
  - task: coverage
    file: dispatch/ci/units/coverage.yml
    params:
      DASHBOARD_HOST: ((dashboard-host))
      UPDATE_COVERAGE: true

