// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import context "context"

import entities "github.com/vmware/dispatch/pkg/event-manager/drivers/entities"
import mock "github.com/stretchr/testify/mock"

// Backend is an autogenerated mock type for the Backend type
type Backend struct {
	mock.Mock
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *Backend) Delete(_a0 context.Context, _a1 *entities.Driver) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Driver) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Deploy provides a mock function with given fields: _a0, _a1
func (_m *Backend) Deploy(_a0 context.Context, _a1 *entities.Driver) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Driver) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: _a0, _a1
func (_m *Backend) Update(_a0 context.Context, _a1 *entities.Driver) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Driver) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
