{{- if .Values.global.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "fullname" . }}-istio-cluster-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["networking.istio.io"]
  resources:
  - "*"
  verbs:
  - "*"
{{- end -}}
