swagger: '2.0'
info:
  description: |
    VMware Serverless - Identity Management APIs
  title: Identity Manager
  contact:
    email: xueyangh@vmware.com
  version: 1.0.0
tags:
- name: authentication
schemes:
- http
- https 
consumes: 
- application/json
produces: 
- application/json

basePath: /
paths:
  /v1/iam:  
    get:
      tags: [authentication]
      summary: if not authenticated, redirect to '/login' endpoint, otherwise, go to the home page
      operationId: login
      responses:
        302:
          description: redirect
          headers:
            Location: 
              description: redirect location
              type: string
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /v1/iam/login/password:
    get:
      tags: [authentication]
      summary: user logs in with username and password, the credientials are forwarded to the external identity provider to exchange for auth token
      operationId: loginPassword
      parameters:
      - in: query
        name: username
        description: user name
        type: string
      - in: query
        name: password
        description: user password
        type: string
      responses:
        200:
          description: OK
          headers:
            Set-Cookie:
              type: string
          schema:
            $ref: "#/definitions/auth"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /login/vmware:
    get:
      tags: [authentication]
      summary: the URL to which the Identity Provider (e.g. vIDM) will redirect the browser after authorization has been granted by the user
      operationId: loginVmware
      parameters:
      - in: query
        name: code
        description: required if authenticated, the authorization code (short-living) generated by the OpenID Provider, used for the client app to exchange for Access Token and/or Id_Token
        type: string
      - in: query
        name: state
        description: OAuth 2.0 state value. required if the Authorization Request included the state parameter. Set to the value received from the Client App (i.e. us).
        type: string
      - in: query
        name: error
        description: required if not authenticated, the error code returned if the End-User denies the request or the End-User authentication fails.
        type: string
      - in: query
        name: error_description
        description: optional, Human-readable ASCII encoded text description of the error.
        type: string
      - in: query
        name: error_uri
        description: optional, URI of a web page that includes additional information about the error.
        type: string
      responses:
        200:
          description: successfully logged in
        302:
          description: successfully logged in, redirect to home page
          headers:
            Location: 
              description: redirect location
              type: string
            Set-Cookie:
              type: string
          schema:
            $ref: "#/definitions/redirect"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /v1/iam/logout:
    get:
      tags: [authentication]
      summary: logout the current user by clearing Application Session Cookies
      operationId: logout
      security:
        - cookie: []
      responses:
        200:
          description: successfully logged out
          headers:
            Set-Cookie:
              type: string
          schema:
            $ref: "#/definitions/message" 
        default:
          description: error
          schema:
            $ref: "#/definitions/error" 
  /v1/iam/home: 
    get:
      summary: an placehold home page, will be redirected to if successfully logged in
      operationId: home
      security:
        - cookie_auth: []
      responses:
        200:
          description: home page
          schema:
            $ref: "#/definitions/message"
        default:
          description: error
          schema:
            $ref: "#/definitions/error" 
  /v1/iam/redirect:
    get:
      summary: redirect to localhost for vs-cli login (testing)
      operationId: redirect
      parameters:
      - in: query
        name: redirect
        description: the local server url redirecting to
        type: string
      responses:
        302: 
          description: redirect
          headers:
            Location: 
              description: redirect location
              type: string
        default:
          description: error
          schema:
            $ref: "#/definitions/error" 

securityDefinitions:
  cookie:
    type: apiKey
    description: use cookies for authentication, when the user already logged in
    in: header
    name: Cookie
definitions:
  redirect:
    type: object
    required:
      - location
    properties:
      location:
        type: string
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
  auth:
    type: object
    properties:
      cookie:
        type: string
  message:
    type: object
    required:
      - message
    properties:
      message:
        type: string
  session:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: string
      name:
        type: string


