apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  client_id:      {{ default "" .Values.app.clientID      | trim | b64enc | quote }}
  client_secret:  {{ default "" .Values.app.clientSecret  | trim | b64enc | quote }}
  cookie_name:    {{ default "" .Values.app.cookieName    | trim | b64enc | quote }}
  cookie_secret:  {{ default "" .Values.app.cookieSecret  | trim | b64enc | quote }}
  cookie_domain:  {{ default "" .Values.app.cookieDomain  | trim | b64enc | quote }}
  cookie_expire:  {{ default "" .Values.app.cookieExpire  | trim | b64enc | quote }}
  cookie_refresh: {{ default "" .Values.app.cookieRefresh | trim | b64enc | quote }}
