///////////////////////////////////////////////////////////////////////
// Copyright (C) 2016 VMware, Inc. All rights reserved.
// -- VMware Confidential
///////////////////////////////////////////////////////////////////////
// Code generated by go-swagger; DO NOT EDIT.

package main

import (
	"log"
	"os"
	"time"

	"github.com/docker/libkv"
	"github.com/docker/libkv/store"
	"github.com/docker/libkv/store/boltdb"
	loads "github.com/go-openapi/loads"
	"github.com/go-openapi/swag"
	flags "github.com/jessevdk/go-flags"
	errors "github.com/pkg/errors"

	"gitlab.eng.vmware.com/serverless/serverless/pkg/config"
	entitystore "gitlab.eng.vmware.com/serverless/serverless/pkg/entity-store"
	iam "gitlab.eng.vmware.com/serverless/serverless/pkg/identity-manager"
	"gitlab.eng.vmware.com/serverless/serverless/pkg/identity-manager/gen/restapi"
	"gitlab.eng.vmware.com/serverless/serverless/pkg/identity-manager/gen/restapi/operations"
)

// NewIdentityStore creates a new entitystore for identity manager
func NewIdentityStore() (entitystore.EntityStore, error) {

	kv, err := libkv.NewStore(
		store.BOLTDB,
		[]string{iam.IdentityManagerFlags.DbFile},
		&store.Config{
			Bucket:            "identity",
			ConnectionTimeout: 1 * time.Second,
			PersistConnection: true,
		},
	)
	if err != nil {
		return nil, errors.Wrap(err, "Error creating/opening the entity store:")
	}
	es := entitystore.New(kv)
	return es, nil
}

func init() {
	boltdb.Register()
	config.Global = config.LoadConfiguration("config.dev.json")
	config.StaticUsers = config.LoadStaticUsers("user.dev.json")
}

func configureFlags() []swag.CommandLineOptionsGroup {
	return []swag.CommandLineOptionsGroup{
		swag.CommandLineOptionsGroup{
			ShortDescription: "Identity Manager Flags",
			LongDescription:  "",
			Options:          &iam.IdentityManagerFlags,
		},
	}
}

func main() {

	swaggerSpec, err := loads.Analyzed(restapi.SwaggerJSON, "")
	if err != nil {
		log.Fatalln(err)
	}

	api := operations.NewIdentityManagerAPI(swaggerSpec)
	server := restapi.NewServer(api)
	defer server.Shutdown()

	parser := flags.NewParser(server, flags.Default)
	parser.ShortDescription = "Identity Manager"
	parser.LongDescription = "VMware Serverless - Identity Management APIs\n"

	optsGroups := configureFlags()
	for _, optsGroup := range optsGroups {
		_, err := parser.AddGroup(optsGroup.ShortDescription, optsGroup.LongDescription, optsGroup.Options)
		if err != nil {
			log.Fatalln(err)
		}
	}

	if _, err := parser.Parse(); err != nil {
		code := 1
		if fe, ok := err.(*flags.Error); ok {
			if fe.Type == flags.ErrHelp {
				code = 0
			}
		}
		os.Exit(code)
	}

	identityStore, err := NewIdentityStore()
	if err != nil {
		log.Fatalln(err)
	}
	authService := iam.NewAuthService(config.Global, identityStore)
	iam.ConfigureHandlers(api, authService)
	if err := server.Serve(); err != nil {
		log.Fatalln(err)
	}
}
