// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"

// OwnershipChecker is an autogenerated mock type for the OwnershipChecker type
type OwnershipChecker struct {
	mock.Mock
}

// CanModify provides a mock function with given fields:
func (_m *OwnershipChecker) CanModify() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ReleaseEntity provides a mock function with given fields:
func (_m *OwnershipChecker) ReleaseEntity() {
	_m.Called()
}
