// Code generated by mockery v1.0.0

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import v1 "github.com/vmware/dispatch/pkg/api/v1"

// SecretsClient is an autogenerated mock type for the SecretsClient type
type SecretsClient struct {
	mock.Mock
}

// CreateSecret provides a mock function with given fields: ctx, organizationID, secret
func (_m *SecretsClient) CreateSecret(ctx context.Context, organizationID string, secret *v1.Secret) (*v1.Secret, error) {
	ret := _m.Called(ctx, organizationID, secret)

	var r0 *v1.Secret
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1.Secret) *v1.Secret); ok {
		r0 = rf(ctx, organizationID, secret)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Secret)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, *v1.Secret) error); ok {
		r1 = rf(ctx, organizationID, secret)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteSecret provides a mock function with given fields: ctx, organizationID, secretName
func (_m *SecretsClient) DeleteSecret(ctx context.Context, organizationID string, secretName string) error {
	ret := _m.Called(ctx, organizationID, secretName)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, organizationID, secretName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSecret provides a mock function with given fields: ctx, organizationID, secretName
func (_m *SecretsClient) GetSecret(ctx context.Context, organizationID string, secretName string) (*v1.Secret, error) {
	ret := _m.Called(ctx, organizationID, secretName)

	var r0 *v1.Secret
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v1.Secret); ok {
		r0 = rf(ctx, organizationID, secretName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Secret)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, organizationID, secretName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListSecrets provides a mock function with given fields: ctx, organizationID
func (_m *SecretsClient) ListSecrets(ctx context.Context, organizationID string) ([]v1.Secret, error) {
	ret := _m.Called(ctx, organizationID)

	var r0 []v1.Secret
	if rf, ok := ret.Get(0).(func(context.Context, string) []v1.Secret); ok {
		r0 = rf(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.Secret)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateSecret provides a mock function with given fields: ctx, organizationID, secret
func (_m *SecretsClient) UpdateSecret(ctx context.Context, organizationID string, secret *v1.Secret) (*v1.Secret, error) {
	ret := _m.Called(ctx, organizationID, secret)

	var r0 *v1.Secret
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1.Secret) *v1.Secret); ok {
		r0 = rf(ctx, organizationID, secret)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Secret)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, *v1.Secret) error); ok {
		r1 = rf(ctx, organizationID, secret)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
