// Code generated by mockery v1.0.0

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import v1 "github.com/vmware/dispatch/pkg/api/v1"

// ServicesClient is an autogenerated mock type for the ServicesClient type
type ServicesClient struct {
	mock.Mock
}

// CreateServiceInstance provides a mock function with given fields: _a0, _a1
func (_m *ServicesClient) CreateServiceInstance(_a0 context.Context, _a1 *v1.ServiceInstance) (*v1.ServiceInstance, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *v1.ServiceInstance
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ServiceInstance) *v1.ServiceInstance); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ServiceInstance)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *v1.ServiceInstance) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteServiceInstance provides a mock function with given fields: ctx, serviceInstanceName
func (_m *ServicesClient) DeleteServiceInstance(ctx context.Context, serviceInstanceName string) error {
	ret := _m.Called(ctx, serviceInstanceName)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, serviceInstanceName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetServiceClass provides a mock function with given fields: ctx, serviceClassName
func (_m *ServicesClient) GetServiceClass(ctx context.Context, serviceClassName string) (*v1.ServiceClass, error) {
	ret := _m.Called(ctx, serviceClassName)

	var r0 *v1.ServiceClass
	if rf, ok := ret.Get(0).(func(context.Context, string) *v1.ServiceClass); ok {
		r0 = rf(ctx, serviceClassName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ServiceClass)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, serviceClassName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetServiceInstance provides a mock function with given fields: ctx, serviceInstanceName
func (_m *ServicesClient) GetServiceInstance(ctx context.Context, serviceInstanceName string) (*v1.ServiceInstance, error) {
	ret := _m.Called(ctx, serviceInstanceName)

	var r0 *v1.ServiceInstance
	if rf, ok := ret.Get(0).(func(context.Context, string) *v1.ServiceInstance); ok {
		r0 = rf(ctx, serviceInstanceName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ServiceInstance)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, serviceInstanceName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListServiceClasses provides a mock function with given fields: _a0
func (_m *ServicesClient) ListServiceClasses(_a0 context.Context) ([]v1.ServiceClass, error) {
	ret := _m.Called(_a0)

	var r0 []v1.ServiceClass
	if rf, ok := ret.Get(0).(func(context.Context) []v1.ServiceClass); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.ServiceClass)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListServiceInstances provides a mock function with given fields: _a0
func (_m *ServicesClient) ListServiceInstances(_a0 context.Context) ([]v1.ServiceInstance, error) {
	ret := _m.Called(_a0)

	var r0 []v1.ServiceInstance
	if rf, ok := ret.Get(0).(func(context.Context) []v1.ServiceInstance); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.ServiceInstance)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
