// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import runtime "github.com/go-openapi/runtime"

// ClientTransport is an autogenerated mock type for the ClientTransport type
type ClientTransport struct {
	mock.Mock
}

// Submit provides a mock function with given fields: _a0
func (_m *ClientTransport) Submit(_a0 *runtime.ClientOperation) (interface{}, error) {
	ret := _m.Called(_a0)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(*runtime.ClientOperation) interface{}); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*runtime.ClientOperation) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
