// Code generated by mockery v1.0.0
package mocks

import functions "gitlab.eng.vmware.com/serverless/serverless/pkg/functions"
import mock "github.com/stretchr/testify/mock"

// FaaSDriver is an autogenerated mock type for the FaaSDriver type
type FaaSDriver struct {
	mock.Mock
}

// Create provides a mock function with given fields: name, exec
func (_m *FaaSDriver) Create(name string, exec *functions.Exec) {
	_m.Called(name, exec)
}

// Delete provides a mock function with given fields: name
func (_m *FaaSDriver) Delete(name string) {
	_m.Called(name)
}

// GetRunnable provides a mock function with given fields: name
func (_m *FaaSDriver) GetRunnable(name string) functions.F {
	ret := _m.Called(name)

	var r0 functions.F
	if rf, ok := ret.Get(0).(func(string) functions.F); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(functions.F)
		}
	}

	return r0
}
