// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import functions "github.com/vmware/dispatch/pkg/functions"
import mock "github.com/stretchr/testify/mock"

// ImageBuilder is an autogenerated mock type for the ImageBuilder type
type ImageBuilder struct {
	mock.Mock
}

// BuildImage provides a mock function with given fields: ctx, faas, fnID, e
func (_m *ImageBuilder) BuildImage(ctx context.Context, faas string, fnID string, e *functions.Exec) (string, error) {
	ret := _m.Called(ctx, faas, fnID, e)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *functions.Exec) string); ok {
		r0 = rf(ctx, faas, fnID, e)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, *functions.Exec) error); ok {
		r1 = rf(ctx, faas, fnID, e)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
