// Code generated by mockery v1.0.0
package mocks

import functions "github.com/vmware/dispatch/pkg/functions"
import mock "github.com/stretchr/testify/mock"

// Validator is an autogenerated mock type for the Validator type
type Validator struct {
	mock.Mock
}

// GetMiddleware provides a mock function with given fields: schemas
func (_m *Validator) GetMiddleware(schemas *functions.Schemas) functions.Middleware {
	ret := _m.Called(schemas)

	var r0 functions.Middleware
	if rf, ok := ret.Get(0).(func(*functions.Schemas) functions.Middleware); ok {
		r0 = rf(schemas)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(functions.Middleware)
		}
	}

	return r0
}
