kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dispatch-api
rules:
  - apiGroups: [""]
    resources: ["namespaces", "secrets", "serviceaccounts"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]

  - apiGroups: ["serving.knative.dev"]
    resources: ["configurations", "configurationgenerations", "routes", "revisions", "revisionuids", "autoscalers", "services"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]

  - apiGroups: ["build.knative.dev"]
    resources: ["builds"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]

  - apiGroups: ["networking.istio.io"]
    resources: ["virtualservices"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
