///////////////////////////////////////////////////////////////////////
// Copyright (c) 2017 VMware, Inc. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
///////////////////////////////////////////////////////////////////////

// Code generated by mockery v1.0.0
package eventmanager

import "github.com/stretchr/testify/mock"

// EventController is an autogenerated mock type for the EventController type
type EventControllerMock struct {
	mock.Mock
}

// Run provides a mock function with given fields:
func (_m *EventControllerMock) Run() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Shutdown provides a mock function with given fields:
func (_m *EventControllerMock) Shutdown() {
	_m.Called()
}

// Update provides a mock function with given fields: _a0
func (_m *EventControllerMock) Update(_a0 *Subscription) {
	_m.Called(_a0)
}
