host: 0.0.0.0
enable-tls: true
tls-certificate: /storage/data/certs/server.crt
tls-certificate-key: /storage/data/certs/server.key
db-file: /storage/db/dispatch.db

local:
  events-gateway: 172.17.0.1:8080
  gateway-tls-port: 443