// Code generated by mockery v1.0.0

// CLOSE THIS FILE AS QUICKLY AS POSSIBLE

package mocks

import mock "github.com/stretchr/testify/mock"

// BaseImageClient is an autogenerated mock type for the BaseImageClient type
type BaseImageClient struct {
	mock.Mock
}

// Add provides a mock function with given fields: i
func (_m *BaseImageClient) Add(i interface{}) error {
	ret := _m.Called(i)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(i)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
