apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Release.Namespace }}
data:
  organization: {{ .Values.organization }}
  serverless.json: |-
    {
      "identity": {
        "oidc_provider": "{{ .Values.identityManager.oidcProvider }}",
        "client_id": "{{ .Values.identityManager.clientId }}",
        "client_secret": "{{ .Values.identityManager.clientSecret }}",
        "redirect_url": "{{ .Values.identityManager.redirectUrl }}",
        "scopes": [
          "{{ .Values.identityManager.scope }}"
        ]
      }
    }
