# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dispatch Serverless Framework
email: bjung@vmware.com
description: >- # this means to ignore newlines until "baseurl:"
  Dispatch is a framework for deploying and managing serverless style applications.
baseurl: "/dispatch" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  berndtj

# Build settings
# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# theme: jekyll-theme-minimal
# plugins:
#   - jekyll-feed
#   - jekyll-sitemap

# Content settings
collections:
  guides:
    output: true
    nav: Guides
  examples:
    output: true
    nav: Examples
  usage:
    output: true
    nav: Usage
  front:
    output: true
  posts:
    nav: Releases
    output:   true

defaults:
  - scope:
      type: guides
    values:
      layout: default
      permalink: /documentation/:collection/:name
  - scope:
      type: examples
    values:
      layout: default
      permalink: /documentation/:collection/:name
  - scope:
      type: usage
    values:
      layout: default
      permalink: /documentation/:collection/:name
  - scope:
      type: posts
    values:
      layout: default
      permalink: /documentation/:collection/:name
  - scope:
      type: front
    values:
      layout: default
      permalink: /documentation/:collection/:name

headers:
  - path: /
    label: Home
  - path: /community
    label: Community
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/