apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  organization: {{ .Values.global.organization }}
  policy.csv: |
    {{- if .Values.global.superUser }}
    p, {{ .Values.global.superUser }}, *, *
    {{- end -}}
