{{- if .Values.ingress.enabled -}}
{{- $tls := default .Values.global.tls .Values.ingress.tls -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-home
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.ingress.home.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ default .Values.global.host .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.home.path }}
            backend:
              serviceName: {{ include "fullname" . }}
              servicePort: {{ .Values.service.externalPort }}
  {{- if $tls.secretName }}
  tls:
    - secretName: {{ $tls.secretName }}
      hosts:
        - {{ default .Values.global.host .Values.ingress.host }}
  {{- end -}}
{{- end -}}
