{{- if .Values.ingress.enabled -}}
{{- $tls := default .Values.global.tls .Values.ingress.tls -}}
{{- $ingress_host := default .Values.global.host .Values.ingress.host -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-home
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.ingress.home.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      error_page 403 = @403.json;
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.home.path }}
            backend:
              serviceName: {{ include "fullname" . }}
              servicePort: {{ .Values.service.externalPort }}
      {{- if $ingress_host }}
      host: {{ $ingress_host }}
      {{- end -}}
  {{- if $tls.secretName }}
  tls:
    - secretName: {{ $tls.secretName }}
      {{- if $ingress_host }}
      hosts:
        - {{ default .Values.global.host .Values.ingress.host }}
      {{- end -}}
  {{- end -}}
{{- end -}}
